# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3"
services:
  datastore:
    build: ./datastore
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: ["gunicorn", "--reload", "-b :8050",  "-t 90", "app:app"]
    container_name: datastore
    hostname: datastore
    volumes:
      - ./datastore/src:/app
    env_file:
      - ./datastore/.env
    networks:
      - datastore_net 
  datastore_client:
    build: ./datastore_client
    depends_on:
      - "datastore"
    ports:
      - 8050:8050
    dns:
      - 8.8.8.8
      - 8.8.4.4
    stdin_open: true
    tty: true
    command: ["gunicorn", "--reload", "-b :8050",  "-t 90", "app:server"]
    container_name: datastore_client
    hostname: datastore_client
    volumes:
      - ./datastore_client/src:/app
    env_file:
      - ./datastore_client/.env
    networks:
      - datastore_net 

networks:
  datastore_net:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 172.16.238.0/24

